### PR TITLE
Add missing library to link

### PR DESCRIPTION
**Pull request by rezso**
/var/uhubuild/work/compile/src/main.cpp:19:10: fatal error: QApplication: Nincs ilyen fájl vagy könyvtár
 #include <QApplication>
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/qterminal.dir/build.make:179: CMakeFiles/qterminal.dir/src/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/uhubuild/work/compile/src/mainwindow.cpp:19:10: fatal error: QDockWidget: Nincs ilyen fájl vagy könyvtár
 #include <QDockWidget>
          ^~~~~~~~~~~~~
compilation terminated.

### CODE REVIEW

**Comment by rezso** [comment]
After this, I get another error:

In file included from /var/uhubuild/work/compile/src/termwidgetholder.h:23:0,
                 from /var/uhubuild/work/compile/src/mainwindow.cpp:33:
/var/uhubuild/work/compile/src/termwidget.h:22:10: fatal error: qtermwidget.h: Nincs ilyen fájl vagy könyvtár
 #include <qtermwidget.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

I don't know, cmake why not appends the existing /usr/include/qtermwidget5 directory.

**Comment by yan12125** [comment]
Let me guess...Did you build qterminal against older qtermwidget? qterminal 0.8.0 should be built with exactly qtermwidget 0.8.0.

**Comment by rezso** [comment]
Yes, I tried with qtermwidget 0.7.1. Qterminal 0.8.0 doesn't requires qtermwidget 0.8.0 in configure.
Note: if I modify the qtermwidget.h include to qtermwidget5/qtermwidget.h, I can compile it.

**Comment by agaida** [comment]
i guess we should solve the problem otherwise:  lxde/qterminal/issues/365

**Comment by agaida** [comment]
fixed with 067f2078188ca14797ed9f81259c1d1507972cf6

**Pull request closed without merging**
