### PR TITLE
Close tabs by middle click.

### PR DESCRIPTION
**Pull request by worblehat**
Implements the feature requested in #142.

### CODE REVIEW

**Comment by pvanek** [comment]
this is very dangerous feature. I don't say it's useless, but maybe it should be configured (default off). @jleclanche your thoughts?

**Comment by jleclanche** [comment]
I agree with you @pvanek, this deserves an option and off by default.

**Comment by worblehat** [comment]
Is there a way to figure if there is a running foreground-process in a tab? We could add an additional confirmation dialog if there is an active process.

**Comment by jleclanche** [comment]
Rejecting.

**Pull request closed without merging**
