### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by m4sk1n**
Please, rebase it

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks!

**Comment by m4sk1n** [comment]
No problem, @yan12125. I hope that one day LXQt will replace my Xfce-based desktop.

**Comment by agaida** [comment]
repleace it now - our bugs are fresh and shiny :)

**Comment by m4sk1n** [comment]
@agaida If there will be any bug in replacement for WhiskerMenu, I'll do it ;)

**Pull request merged**
