### PR TITLE
A real shortcut editor

### PR DESCRIPTION
**Pull request by tsujan**
Fixes https://github.com/lxde/qterminal/issues/398.

### CODE REVIEW

**Comment by kdave** [comment]
Works fine. I don't know if removing the shortcut is some standardized way, after some experimenting I figured out that pressing Shift while editing would remove the shortcuts one by one. This could be noted somewhere in the panel.

**Comment by tsujan** [comment]
> I don't know if removing the shortcut is some standardized way

`Alt` removes the whole shortcut.

**Comment by tsujan** [comment]
BTW,

(1) Things like shortcut removal are included in `QKeySequenceEdit`.

(2) There's yet another instance of shortcut input in the Dropdown page, for which I'll add a `QKeySequenceEdit` later -- in another PR.

**Comment by agaida** [comment]
GTM

**Pull request merged**
